### ISSUE TITLE
Import

### ISSUE THREAD

**Issue by AnowarCST** [rbobko93/lex-small-talk-bot#1]
How to import it on Lex?

**Comment by M4C4R** [comment]
1. Download the file, compress it into a zip.
2. On the AWS Lex console under bots, click `Actions > Import` and select the zip.

This will create a new bot with all the intents AND import all the intents into your account.
You can then delete the created bot and use the intents in existing bots by selecting `Search existing intents` when adding an intent.

**Comment by rbobko93** [comment]
@M4C4R described it perfectly. Sorry for not responding, but I didn't see that issue being created. Closing since resolved.
